/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expensebook;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;

/**
 *
 * @author softpoint
 */
public class DashboardPage extends javax.swing.JFrame {

    /**
     * Creates new form DashboardPage
     */
    public DashboardPage() {
        initComponents();
        setOnlineBtnValue();
        setofflineBtnValue();
        this.getContentPane().setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("Jdbc:mysql://localhost:3306/expenses_book", "root", "");
            String sql = "select username from login_table";
            PreparedStatement pst = con.prepareStatement(sql);
           ResultSet rs = pst.executeQuery();
           while(rs.next()){
               lblWelcome.setText("Welcome "+rs.getString("username"));
           }
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnOnlineIn = new javax.swing.JButton();
        btnOnlineOut = new javax.swing.JButton();
        btnOnlineNet = new javax.swing.JButton();
        btnOnlineExpenses = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnOfflineIn = new javax.swing.JButton();
        btnOfflineOut = new javax.swing.JButton();
        btnOfflineNet = new javax.swing.JButton();
        btnOfflineExpenses = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Online Expenses");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Money IN");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 90, 80, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Money OUT");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 140, 100, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Net Balance");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 100, 30));

        btnOnlineIn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnOnlineIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnlineInActionPerformed(evt);
            }
        });
        jPanel1.add(btnOnlineIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 120, 30));

        btnOnlineOut.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnOnlineOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnlineOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnOnlineOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 120, 30));

        btnOnlineNet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnOnlineNet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnlineNetActionPerformed(evt);
            }
        });
        jPanel1.add(btnOnlineNet, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, 30));

        btnOnlineExpenses.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnOnlineExpenses.setText("ADD EXPENSES");
        btnOnlineExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnlineExpensesActionPerformed(evt);
            }
        });
        jPanel1.add(btnOnlineExpenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensebook/dashboard.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Offline Expenses");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 190, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Money IN");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Money OUT");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Net Balance");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        btnOfflineIn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnOfflineIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfflineInActionPerformed(evt);
            }
        });
        jPanel4.add(btnOfflineIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 120, 30));

        btnOfflineOut.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnOfflineOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfflineOutActionPerformed(evt);
            }
        });
        jPanel4.add(btnOfflineOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 120, 30));

        btnOfflineNet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnOfflineNet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfflineNetActionPerformed(evt);
            }
        });
        jPanel4.add(btnOfflineNet, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, 30));

        btnOfflineExpenses.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnOfflineExpenses.setText("ADD EXPENSES");
        btnOfflineExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfflineExpensesActionPerformed(evt);
            }
        });
        jPanel4.add(btnOfflineExpenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 130, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensebook/dashboard.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 300));

        lblWelcome.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblWelcome.setText("Welcome ");

        btnRefresh.setBackground(new java.awt.Color(255, 255, 255));
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensebook/refresh.png"))); // NOI18N
        btnRefresh.setToolTipText("Refresh");
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnMenu.setBackground(new java.awt.Color(255, 255, 255));
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensebook/m.png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWelcome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOnlineExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnlineExpensesActionPerformed
        OnlineDashboard od = new OnlineDashboard();
        od.setVisible(true);

    }//GEN-LAST:event_btnOnlineExpensesActionPerformed

    private void btnOfflineExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfflineExpensesActionPerformed
        OfflineDashboard od = new OfflineDashboard();
        od.setVisible(true);
    }//GEN-LAST:event_btnOfflineExpensesActionPerformed

    private void btnOnlineNetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnlineNetActionPerformed
         ResultSet rs=null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("Jdbc:mysql://localhost:3306/expenses_book", "root", "");
            String sql = "select * from online_expenses";
            PreparedStatement pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
        } catch (Exception e) {
            System.out.println(e);
        }
        ShowNetExpenses ob=new ShowNetExpenses();
        ob.getTableInfo(rs,"online_expenses");
        ob.setVisible(true);
    }//GEN-LAST:event_btnOnlineNetActionPerformed

    private void btnOfflineNetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfflineNetActionPerformed
        // TODO add your handling code here:
        ResultSet rs=null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("Jdbc:mysql://localhost:3306/expenses_book", "root", "");
            String sql = "select * from offline_expenses";
            PreparedStatement pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
        } catch (Exception e) {
            System.out.println(e);
        }
        ShowNetExpenses ob=new ShowNetExpenses();
        ob.getTableInfo(rs,"offline_expenses");
        ob.setVisible(true);
    }//GEN-LAST:event_btnOfflineNetActionPerformed

    private void btnOnlineInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnlineInActionPerformed
        // TODO add your handling code here:
        ResultSet rs=null;
        ResultSet rsSum=null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("Jdbc:mysql://localhost:3306/expenses_book", "root", "");
            String sql = "select * from online_expenses where credit_debit='Credit'";
            String sqlSum = "select sum(amount) from online_expenses where credit_debit='Credit'";
            PreparedStatement pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            PreparedStatement pstSum = con.prepareStatement(sqlSum);
            rsSum = pstSum.executeQuery();
        } catch (Exception e) {
            System.out.println(e);
        }
        ShowInExpenses ob=new ShowInExpenses();
        ob.getTableInfo(rs,rsSum,"online_expenses");
        ob.setVisible(true);
    }//GEN-LAST:event_btnOnlineInActionPerformed

    private void btnOfflineInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfflineInActionPerformed
        // TODO add your handling code here:
        ResultSet rs=null;
        ResultSet rsSum=null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("Jdbc:mysql://localhost:3306/expenses_book", "root", "");
            String sql = "select * from offline_expenses where credit_debit='Credit'";
            String sqlSum = "select sum(amount) from offline_expenses where credit_debit='Credit'";
            PreparedStatement pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            PreparedStatement pstSum = con.prepareStatement(sqlSum);
            rsSum = pstSum.executeQuery();
        } catch (Exception e) {
            System.out.println(e);
        }
        ShowInExpenses ob=new ShowInExpenses();
        ob.getTableInfo(rs,rsSum,"offline_expenses");
        ob.setVisible(true); 
    }//GEN-LAST:event_btnOfflineInActionPerformed

    private void btnOnlineOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnlineOutActionPerformed
        // TODO add your handling code here:
        ResultSet rs=null;
        ResultSet rsSum=null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("Jdbc:mysql://localhost:3306/expenses_book", "root", "");
            String sql = "select * from online_expenses where credit_debit='Debit'";
            String sqlSum = "select sum(amount) from online_expenses where credit_debit='Debit'";
            PreparedStatement pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            PreparedStatement pstSum = con.prepareStatement(sqlSum);
            rsSum = pstSum.executeQuery();
        } catch (Exception e) {
            System.out.println(e);
        }
        ShowOutExpenses ob=new ShowOutExpenses();
        ob.getTableInfo(rs,rsSum,"online_expenses");
        ob.setVisible(true);
    }//GEN-LAST:event_btnOnlineOutActionPerformed

    private void btnOfflineOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfflineOutActionPerformed
        // TODO add your handling code here:
        ResultSet rs=null;
        ResultSet rsSum=null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("Jdbc:mysql://localhost:3306/expenses_book", "root", "");
            String sql = "select * from offline_expenses where credit_debit='Debit'";
            String sqlSum = "select sum(amount) from offline_expenses where credit_debit='Debit'";
            PreparedStatement pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            PreparedStatement pstSum = con.prepareStatement(sqlSum);
            rsSum = pstSum.executeQuery();
        } catch (Exception e) {
            System.out.println(e);
        }
        ShowOutExpenses ob=new ShowOutExpenses();
        ob.getTableInfo(rs,rsSum,"offline_expenses");
        ob.setVisible(true);
    }//GEN-LAST:event_btnOfflineOutActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        setofflineBtnValue();
        setOnlineBtnValue();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        DashMenu frm=new DashMenu();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    public void setOnlineBtnValue() {
        try {
            double net=0;
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/expenses_book","root","");
            String sql="SELECT SUM(amount) FROM online_expenses Where Credit_Debit='Credit'";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
                net=rs.getDouble(1);
                btnOnlineIn.setText("Rs "+rs.getDouble(1));
            }
            String sql1="SELECT SUM(amount) FROM online_expenses Where Credit_Debit='Debit'";
            PreparedStatement pst1=con.prepareStatement(sql1);
            ResultSet rs1=pst1.executeQuery();
            while(rs1.next()){
                net=net-rs1.getDouble(1);
                btnOnlineOut.setText("Rs "+rs1.getDouble(1));
            }
            btnOnlineNet.setText("Rs "+net);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public void setofflineBtnValue() {
        try {
            double net=0;
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/expenses_book","root","");
            String sql="SELECT SUM(amount) FROM offline_expenses Where Credit_Debit='Credit'";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
                net=rs.getDouble(1);
                btnOfflineIn.setText("Rs "+rs.getDouble(1));
            }
            String sql1="SELECT SUM(amount) FROM offline_expenses Where Credit_Debit='Debit'";
            PreparedStatement pst1=con.prepareStatement(sql1);
            ResultSet rs1=pst1.executeQuery();
            while(rs1.next()){
                net=net-rs1.getDouble(1);
                btnOfflineOut.setText("Rs "+rs1.getDouble(1));
            }
            btnOfflineNet.setText("Rs "+net);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DashboardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DashboardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DashboardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DashboardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DashboardPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnOfflineExpenses;
    private javax.swing.JButton btnOfflineIn;
    private javax.swing.JButton btnOfflineNet;
    private javax.swing.JButton btnOfflineOut;
    private javax.swing.JButton btnOnlineExpenses;
    private javax.swing.JButton btnOnlineIn;
    private javax.swing.JButton btnOnlineNet;
    private javax.swing.JButton btnOnlineOut;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
